### ISSUE TITLE
Afl-clang-fast (based on clang-6.0 ) can't be used to compile target v8 engine

### ISSUE THREAD

**Issue by qiaoguanli** [sslab-gatech/DIE#13]
v8 engine used clang(version 12.0.0) which would be download while git the source code to compile the whole project.
But afl-clang was built based on clang-6.0, there were too many options which are unknow for that.
How did you deal with that ?
<img width="966" alt="16032746465094" src="https://user-images.githubusercontent.com/10720032/96706060-aa828700-13c8-11eb-895f-0744c9821a64.png">

**Comment by thdusdl1219** [comment]
I didn't see this problem when I did the experiment. It seems v8's compiling toolchain or compiling option is different from what I did. So, I updated compilation script for v8 and checked it's working with the latest v8 (which uses clang-12). Thanks for reporting!

**Comment by qiaoguanli** [comment]
Thanks for your reply, there are still same problem on my environment with your new commit. Is that your afl-clang-fast compiled based on clang-6.0?

**Comment by thdusdl1219** [comment]
Yes. It compiled based on clang-6.0.
```
❯ ./afl-clang-fast++ --version                                                                                                                                                                                                
afl-clang-fast 2.52b by <lszekeres@google.com>
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

**Comment by qiaoguanli** [comment]
Okey, I found it. It works after adding `remove(cmdline, "-Wunknown-warning-option")` in the `proxy.py`. Many thanks for your share.
