### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by adrian-rt** [sslab-gatech/DIE#3]
I tried multiple clang versions, I installed clang-6.0 especially for this.

[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. ./afl-clang -O3 -funroll-loops -Wall -Wno-unused-variable -Wno-unused-function -Wno-unused-result -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" test-instr.c -o test-instr -ldl
echo 0 | ./afl-showmap -m none -q -o .test-instr0 ./test-instr
echo 1 | ./afl-showmap -m none -q -o .test-instr1 ./test-instr

Oops, the instrumentation does not seem to be behaving correctly!

Please ping <lcamtuf@google.com> to troubleshoot the issue.

make: *** [Makefile:95: test_build] Error 1
~/Downloads/DIE

**Comment by SioYooo** [comment]
Hi Adrian,

Did you fixed this issue or not?
If you fixed this issue, could you please share the method how you fixed it?

Thanks a lot. I have the same issue when I was trying to install the llvm_mode.
