### ISSUE TITLE
Instructions to use new corpus

### ISSUE THREAD

**Issue by Changochen** [sslab-gatech/DIE#6]
Hi, I found that `https://github.com/sslab-gatech/DIE/blob/master/fuzz/scripts/make_initial_corpus.py#L59` simply copies the `.js` and `.t` files. If we want to add new test cases, how do we generate the `.t` files for js files?

**Comment by thdusdl1219** [comment]
I updated typer. Please check new `Readme.md` and `fuzz/TS/typer`.

**Comment by Changochen** [comment]
@thdusdl1219 Appreciated for the help! A minor issue. The `CPair` should be `Pair` in `https://github.com/sslab-gatech/DIE/blob/master/fuzz/TS/typer/typer.ts#L7`

**Comment by thdusdl1219** [comment]
It seems legacy code hasn't removed. Thanks!
